services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "8081:80"
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - app-network

  collabora_online:
    build:
      context: ./src/view
    image: collabora:latest
    container_name: collabora_online
    restart: always
    ports:
      - "9980:9980"
    cap_add:
      - SYS_ADMIN
    environment:
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false --o:user_interface.use_integration_theme=false --o:storage.wopi.alias_groups.mode=groups
    networks:
      - app-network
    depends_on:
      - nextcloud
      - skopeo_controller

  skopeo_controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: skopeo-controller:latest
    container_name: skopeo_controller
    restart: always
    ports:
      - "9000:9000"
    networks:
      - app-network

volumes:
  nextcloud_data:

networks:
  app-network:
    driver: bridge
