services:
  collabora_online:
    build:
      context: .
      dockerfile: ./src/view/Dockerfile
    image: collabora:latest
    container_name: collabora_online
    restart: always
    ports:
      - "9980:9980"
    cap_add:
      - SYS_ADMIN
    environment:
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    networks:
      - app-network
    depends_on:
      - skopeo_controller

  skopeo_controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: skopeo-controller:latest
    container_name: skopeo_controller
    restart: always
    networks:
      - app-network

volumes:
  nextcloud_data:

networks:
  app-network:
    driver: bridge
