services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "8081:80"
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - app-network

  collabora_online:
    build:
      context: ./src/view/docker/from-packages
    image: collabora:latest
    container_name: collabora_online
    restart: always
    ports:
      - "9980:9980"
    cap_add:
      - MKNOD
    command:
      - /start-collabora-online.sh
      - --o:server_name=localhost:9980
      - --o:ssl.enable=false
      - --o:wopi.host='.*'
    networks:
      - app-network
    depends_on:
      - nextcloud
      - ai_controller

  ai_controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: skopeo-controller:latest
    container_name: skopeo_controller
    restart: always
    ports:
      - "9000:9000"
    networks:
      - app-network

volumes:
  nextcloud_data:

networks:
  app-network:
    driver: bridge
