services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - app-network
    depends_on:
      - collabora_online
      - skopeo_controller

  collabora_online:
    build:
      context: .
      dockerfile: ./src/view/Dockerfile
    image: collabora:latest
    container_name: collabora_online
    restart: always
    cap_add:
      - SYS_ADMIN
    environment:
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:storage.wopi.host=office.localhost --o:server_name=office.localhost --o:storage.wopi.host_allow_list=office.localhost
    networks:
      - app-network
    depends_on:
      - skopeo_controller

  skopeo_controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: skopeo-controller:latest
    container_name: skopeo_controller
    restart: always
    networks:
      - app-network

volumes:
  nextcloud_data:

networks:
  app-network:
    driver: bridge
